name: meine_wunschliste
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  intl:
  image_picker:
  shared_preferences:
  permission_handler:
  flutter_local_notifications:
  timezone:
  flutter_colorpicker:
  flutter_phoenix:
  connectivity_plus:
  firebase_core:
  cloud_firestore:
  firebase_remote_config:
  firebase_database:
  firebase_auth:
  flutter_bloc:
  path_provider:
  realm:
  uuid:
  get_it:
  get:
  google_sign_in:
  sign_in_with_apple:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Kinoble
      fonts:
        - asset: assets/fonts/Kinoble-Medium.ttf
        - asset: assets/fonts/Kinoble-MediumItalic.ttf
          weight: 500
  assets:
    - assets/fonts/
    - assets/icons/logo.png
    - assets/icons/show.png
    - assets/icons/unshow.png
    - assets/icons/uncomplete.png
    - assets/icons/add_task.png
    - assets/icons/delete.png
    - assets/icons/redact.png
    - assets/icons/stop.png
    - assets/icons/order.png
    - assets/icons/tasks.png
    - assets/icons/theme_settings.png
    - assets/icons/add_task_tree.png
    - assets/icons/add_category.png
    - assets/icons/complete.png
    - assets/icons/profile.png
    - assets/background.jpeg
