// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqDVmkem9bN0zx9Icqufub_gzNnCyOovY',
    appId: '1:915187532518:android:9325ad63cf42e0e93c3127',
    messagingSenderId: '915187532518',
    projectId: 'meine-wunschliste',
    storageBucket: 'meine-wunschliste.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUzH7QUOe33qEpoMswKVwaoJVjtyZFRcA',
    appId: '1:915187532518:ios:1bb1ba4d79273edd3c3127',
    messagingSenderId: '915187532518',
    projectId: 'meine-wunschliste',
    storageBucket: 'meine-wunschliste.appspot.com',
    androidClientId: '915187532518-dcrgn8r0l5aup2flsnlcnquqpfab3f2r.apps.googleusercontent.com',
    iosClientId: '915187532518-aaaoqt3n93mijrr3d92ls1pdisncr2j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.meineWunschliste',
  );
}
